import { useEffect, useRef, useState } from 'react';
const links = [['Classes','classes'],['Method','method'],['Studio','studio'],['Instructors','instructors'],['Schedule','schedule']];
export function Header() {
 const [open,setOpen] = useState(false);
 const toggle = useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return; const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open]);
 return <header className="site-header"><a className="wordmark" href="#" aria-label="Sora Movement home">sora<span>movement</span></a><button ref={toggle} className="menu-toggle" aria-expanded={open} aria-controls="navigation" onClick={()=>setOpen(!open)}>{open?'Close':'Menu'} <span aria-hidden="true">{open?'−':'+'}</span></button><nav id="navigation" className={open?'navigation is-open':'navigation'} aria-label="Main navigation">{links.map(([name,id])=><a key={id} href={'#'+id} onClick={()=>setOpen(false)}>{name}</a>)}<a className="button header-book" href="#schedule" onClick={()=>setOpen(false)}>Book a class</a></nav></header>
}
export function Footer(){return <footer id="contact" className="footer"><div className="footer-top"><a className="wordmark" href="#">sora<span>movement</span></a><p>A little more strength.<br/>A little more room to move.</p></div><div className="footer-columns"><div><h3>Find your movement</h3><a href="#classes">Classes</a><a href="#method">Method</a><a href="#studio">Studio</a><a href="#schedule">Schedule</a></div><div><h3>Come by</h3><p>Monday–Friday, 07:00–20:00<br/>Saturday, 08:30–14:00<br/>Sunday, time to recharge.</p></div><div><h3>Let’s talk</h3><a href="mailto:hello@soramovement.example">hello@soramovement.example</a><p>Studio location coming soon.</p><a href="https://www.instagram.com/" target="_blank" rel="noreferrer">Instagram <span className="sr-only">(opens in a new tab)</span> ↗</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Sora Movement</span><span>A fictional studio. A real love of movement.</span></div></footer>}
